longhorn:
  defaultSettings:
    defaultDataPath: /var/mnt/longhorn-fast
  persistence:
    reclaimPolicy: Retain
  preUpgradeChecker:
    jobEnabled: false
  defaultBackupStore:
    backupTarget: s3://pvc-backups@us-east-1/
    backupTargetCredentialSecret: longhorn-backups-s3
