longhorn:
  defaultSettings:
    defaultDataPath: /var/mnt/longhorn-fast
  persistence:
    reclaimPolicy: Retain
  preUpgradeChecker:
    jobEnabled: false
  defaultBackupStore:
    backupTarget: "nfs://192.168.3.98:/tank/backups/pvc?nfsOptions=rw,nolock"
