apiVersion: v1
kind: Secret
metadata:
  name: authentik-creds
  namespace: authentik
type: Opaque
stringData:
  pg_user: "{{ .Values.pgUser }}"
  pg_pass: "{{ .Values.pgPass }}"
  secret_key: "{{ .Values.secretKey }}"
  email_user: "{{ .Values.emailUser }}"
  email_pass: "{{ .Values.emailPass }}"
