{{ if .Values.s3AccessKeyID }}
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-backups-s3
  namespace: longhorn-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "{{ .Values.s3AccessKeyID }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.s3SecretAccessKey }}"
  AWS_ENDPOINTS: "{{ .Values.s3Endpoints}}"
{{ end }}
