{{ if .Values.pangolinEndpoint }}
apiVersion: v1
kind: Secret
metadata:
  name: newt-credentials
  namespace: newt
type: Opaque
stringData:
  PANGOLIN_ENDPOINT: "{{ .Values.pangolinEndpoint }}"
  NEWT_ID: "{{ .Values.newtId }}"
  NEWT_SECRET: "{{ .Values.newtSecret }}"
{{ end }}
