authentik:
  authentik:
    postgresql:
      name: authentik_alpha
    email:
      from: "Authentik dev <authentik@cloud.konstakanniainen.dev>"

  server:
    ingress:
      hosts:
        - login.konstakanniainen.dev
