config:
  existingVolumeName: pvc-c4787398-a167-4fff-a262-0ef2df254443

media:
  existingVolumeName: pvc-a0207e4a-5247-4d0e-af8a-a36ee78f9723

jellyfin:
  persistence:
    config:
      existingClaim: "jellyfin-config"
    media:
      existingClaim: "jellyfin-media"
