apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.namespace }}-nfs"
  namespace: "{{ .Values.namespace }}"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-default
