apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: "{{ .Values.namespace }}"
spec:
  containers:
    - name: test
      image: busybox
      command:
        [
          "sh",
          "-c",
          "echo 'NFS works' > /data/test.txt && cat /data/test.txt && sleep 3600",
        ]
      volumeMounts:
        - name: nfs-data
          mountPath: /data
  volumes:
    - name: nfs-data
      persistentVolumeClaim:
        claimName: "{{ .Values.namespace }}-nfs"
