apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-app
  name: test-deployment
  namespace: "{{ .Values.namespace }}"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
        - name: test-container
          image: busybox
          command:
            [
              "sh",
              "-c",
              "echo 'NFS works' > /data/test.txt && cat /data/test.txt && sleep 3600",
            ]
          volumeMounts:
            - name: nfs-data
              mountPath: /data
      volumes:
        - name: nfs-data
          persistentVolumeClaim:
            claimName: "{{ .Values.namespace }}-nfs"
