apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cronjobs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: http://git.internal/konstaka/homelab.git
    path: cronjobs
    targetRevision: HEAD
  destination:
    namespace: cronjobs
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
