apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver-nfs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: http://192.168.3.102:3000/appelstroopwafel/homelab.git
    path: csi-driver-nfs
    targetRevision: HEAD
    helm:
      valueFiles:
        - environments/values-beta.yaml
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
