apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver-nfs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: http://git.internal/konstaka/homelab.git
    path: csi-driver-nfs
    targetRevision: HEAD
    helm:
      valueFiles:
        - environments/values-alpha.yaml
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
