apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helloworld
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - cluster: alpha
            url: https://kube.cluster-alpha.home.arpa:6443
          - cluster: beta
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: "hello-{{`{{ .cluster }}`}}"
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      project: default
      source:
        repoURL: http://192.168.3.102:3000/appelstroopwafel/homelab.git
        path: helloworld
        targetRevision: HEAD
      destination:
        namespace: helloworld
        server: "{{`{{ .url }}`}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
