apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-k8s
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  source:
    repoURL: http://192.168.3.102:3000/appelstroopwafel/homelab.git
    path: helloworld
    targetRevision: HEAD
  destination:
    namespace: helloworld
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
