{{ if .Values.featureFlags.jellyfin }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: https://forge.konstakanniainen.dev:444/konstaka/homelab.git
    path: jellyfin
    targetRevision: HEAD
    helm:
      valueFiles:
        - "values.yaml"
        - "environments/values-{{ .Values.cluster }}.yaml"
  destination:
    namespace: jellyfin
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{ end }}