apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: toolbox
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: http://git.internal/konstaka/homelab.git
    path: toolbox
    targetRevision: HEAD
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
