{{ if .Values.jellyfin.persistence.config.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: jellyfin:/PersistentVolumeClaim:jellyfin/jellyfin-config
    volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
    volume.kubernetes.io/storage-provisioner: driver.longhorn.io
  finalizers:
    - kubernetes.io/pvc-protection
  name: jellyfin-config
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: {{ .Values.config.existingVolumeName }}
{{ end }}