csi-driver-nfs:
  controller:
    replicas: 2

  storageClass:
    create: true
    name: nfs-default
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
    parameters:
      subDir: "${pvc.metadata.namespace}/${pvc.metadata.name}"
      mountPermissions: "0777"
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    mountOptions:
      - nfsvers=4.2
