apiVersion: v2
name: cert-manager-desec-webhook
type: application
version: 1.0.0
appVersion: 1.0.0

dependencies:
  - name: cert-manager-desec-webhook
    version: 0.1.1
    repository: oci://ghcr.io/pr0ton11/helm
