apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-resource
  namespace: longhorn-system
data:
  default-resource.yaml: |
    "backup-target": "nfs://192.168.3.98:/tank/backups/pvc?nfsOptions=rw,nolock"
