config:
  existingVolumeName: pvc-99f8646f-a42a-43e6-96ab-3bd567cec7fc

media:
  existingVolumeName: pvc-46f348e6-33e2-4650-9b66-17eff515155f

jellyfin:
  persistence:
    config:
      existingClaim: "jellyfin-config"
    media:
      existingClaim: "jellyfin-media"
      size: "5Gi"
  volumes:
    - name: series
      nfs:
        server: 192.168.3.98
        path: /tank/data/media/series
    - name: movies
      nfs:
        server: 192.168.3.98
        path: /tank/data/media/movies
    - name: radio
      nfs:
        server: 192.168.3.98
        path: /tank/data/media/radio
  volumeMounts:
    - mountPath: /series
      name: series
      readOnly: true
    - mountPath: /movies
      name: movies
      readOnly: true
    - mountPath: /radio
      name: radio
      readOnly: true
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: jellyfin-buffering@kubernetescrd
    hosts:
      - host: jellyfin.kohmis.fi
        paths:
          - path: /
            pathType: Prefix
  resources:
    limits:
      cpu: 1500m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 1Gi
