jellyfin:
  persistence:
    config:
      existingClaim: "jellyfin-config"
    media:
      size: "5Gi"
      #existingClaim: "jellyfin-media"
  volumes:
    - name: series
      nfs:
        server: 192.168.3.98
        path: /tank/data/media/series
    - name: movies
      nfs:
        server: 192.168.3.98
        path: /tank/data/media/movies
    - name: radio
      nfs:
        server: 192.168.3.98
        path: /tank/data/media/radio
  volumeMounts:
    - mountPath: /series
      name: series
      readOnly: true
    - mountPath: /movies
      name: movies
      readOnly: true
    - mountPath: /radio
      name: radio
      readOnly: true
